config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get '/pages/home', to: 'pages#home', as: 'home'
  get '/pages/four_oven_cooker', to: 'pages#four_oven_cooker', as: 'four_oven_gas'
  get '/pages/four_oven_cooker_electric', to: 'pages#four_oven_cooker_electric', as: 'four_oven_electric'
  get '/pages/three_oven_cooker', to: 'pages#three_oven_cooker', as: 'three_oven'
  get '/pages/two_oven_cooker', to: 'pages#two_oven_cooker', as: 'two_oven_gas'
  get '/pages/two_oven_cooker_electric', to: 'pages#two_oven_cooker_electric', as: 'two_oven_electric'
  get '/pages/city_sixty_traditional', to: 'pages#city_sixty_traditional', as: 'city_sixty_traditional'
  get '/pages/city_sixty_contemporary', to: 'pages#city_sixty_contemporary', as: 'city_sixty_contemporary'
  get '/pages/aga_companion', to: 'pages#aga_companion', as: 'aga_companion'

  post '/pages/update_image'

  resources :pages
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]

  namespace :admin do
    resources :pages, only: [:index, :new, :create, :edit, :destroy, :update] do
      collection { post :sort }
    end
  end

  get "/admin", :to => redirect("/admin/pages")

  root to: "pages#home"
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Creekstone Cookers Contact",
      :to => "laurie@creekstonecookers.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id           :integer          not null, primary key
#  created_at   :datetime
#  updated_at   :datetime
#  title        :string(255)
#  content      :text
#  is_home_page :boolean          default(FALSE)
#  order        :integer
#  ancestry     :string(255)
#

class Page < ActiveRecord::Base
  has_ancestry
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  validates :title, presence: true

  NAV_LOCATIONS = ["Side Bar", "Main Nav"]
  NO_SIDE_BAR = ['four_oven_cooker_gas', 'four_oven_cooker_electric', 'two_oven_cooker_gas']

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  layout 'admin'

  before_filter :authenticate

  def index
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.friendly.find(params[:id])
  end

  def create
    @page = Page.new(pages_params)
    if @page.save
      flash[:success] = 'Page created successfully'
      redirect_to edit_admin_page_path(@page)
    else
      render :new
    end
  end

  def destroy
    Page.friendly.find(params[:id]).destroy
    flash[:success] = 'Page Successfully destroyed'
    redirect_to admin_pages_path
  end

  def sort
    params[:page][:position].each_with_index do |id, index|
      Page.friendly.find(id).update_attributes(position: index)
    end
    render nothing: true
  end

  def update
    page = Page.friendly.find(params[:id])
    if page.title != pages_params[:title]
      page.slug = nil
    end
    page.update!(pages_params)
    redirect_to page_path(page)
  end

  private

  def pages_params
    params.require(:page).permit(:title, :content, :order, :parent_id, :nav_location, :position => [])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_nav

  APP_DOMAIN = 'www.creekstonecookers.com'

  def ensure_domain
    if request.env['HTTP_HOST'] != APP_DOMAIN
      puts request.fullpath
      # HTTP 301 is a "permanent" redirect
      redirect_to "http://#{APP_DOMAIN}#{request.fullpath}", :status => 301
    end
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "creekstone" && password == "Cr33kst0n3!"
    end
  end

  def get_nav
    @pages_nav = Page.all.order('order asc')
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:success] = 'Thank you for your message!'
      redirect_to new_contact_path
    else
      flash[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
    render layout: false
  end

  def create
    @page = Page.new(pages_params)
    if @page.save
      redirect_to page_path(@page), notice: 'Page created successfully'
    else
      render :new
    end
  end

  def show
    @page = Page.friendly.find(params[:id])
    if Page::NO_SIDE_BAR.include?(@page.title)
      render layout: 'no_side_nav'
    end

    if request.path != page_path(@page)
      redirect_to @page, status: :moved_permanently
    end
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(pages_params)
      redirect_to page_path(@page), notice: 'Page updated successfully'
    else
      render :edit
    end
  end

  def home
    @page = Page.where(title: 'Home').last
  end

  def update_image
    @image = params[:image]
    @type = params[:type]
  end

  def four_oven_cooker_electric
    render layout: 'no_side_nav'
  end

  def four_oven_cooker_gas
    render layout: 'no_side_nav'
  end

  def city_sixty_traditional
    render layout: 'no_side_nav'
  end

  private

  def pages_params
    params.require(:page).permit(:title, :content, :order, :nav_location)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)                          # Method definition
    base_title = "Creekstone Cookers"                 # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{base_title} | #{page_title}"                 # String interpolation
    end
  end

  def twitterized_type(type)
    case type
      when "alert"
        "alert-block"
      when "error"
        "alert-error"
      when "notice"
        "alert-info"
      when "success"
        "alert-success"
      else
        type.to_s
    end
  end

  def root_navigation
    roots = Page.where.not(nav_location: "Side Bar").roots.order("position")
  end

  def side_bar_navigation
    roots = Page.where(nav_location: "Side Bar").roots.order("position")
  end

  def admin_pages
    Page.roots.order("position")
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/_side_nav.html.haml
.panel-group#accordion
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{'data-toggle' => "collapse", 'data-parent' => "#accordion", href: "#collapseOne"} Pages
    .panel-collapse.collapse.in#collapseOne
      .panel-body
        .pages-sortable{"data-update-url" => "#{sort_admin_pages_url}"}
          - admin_pages.each do |page|
            .page-title{'data-page-id' => "#{page.id}"}
              = link_to page.title, edit_admin_page_path(page)
            - unless page.children.empty?
              %ul.page-children
                - page.children.each do |ancestor|
                  %li.page-title.page-ancestor{'data-page-id' => "#{ancestor.id}"}
                    = link_to ancestor.title, edit_admin_page_path(ancestor)
                  - unless ancestor.children.empty?
                    %ul.page-children
                      - ancestor.children.each do |child|
                        %li.page-title.page-ancestor{'data-page-id' => "#{child.id}"}
                          = link_to child.title, edit_admin_page_path(child)



        .page-new= link_to "New Page...", new_admin_page_path

  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{'data-toggle' => "collapse", 'data-parent' => "#accordion", href: "#collapseTwo"} Events
    .panel-collapse.collapse#collapseTwo
      .panel-body
        Events Coming Soon

app/views/admin/pages/edit.html.haml
.row
  .col-xs-12.col-md-3
    = render 'side_nav'

  .col-xs-12.col-md-9
    #page-content
      %h2 Edit Page

      = link_to page_path(@page), class: 'btn btn-default btn-sm' do
        %span.glyphicon.glyphicon-ok-sign
        View Page

      = link_to admin_page_path(@page), class: 'btn btn-danger btn-sm', method: 'delete' do
        %span.glyphicon.glyphicon-remove
        Delete Page


      = simple_form_for @page, :url => url_for(:action => 'update', :controller => 'pages'), html: { role: 'form', style: 'margin-top: 15px;' } do |f|
        .form-group
          = f.input :title, placeholder: 'Page Title', input_html: { style: 'width: 100%' }

        .form-group
          = f.input :content, :as => :ckeditor, input_html: { :ckeditor => {:toolbar => 'Full'} }

        .form-group
          = f.label :parent_id
          = f.collection_select :parent_id, Page.order(:title), :id, :title, include_blank: true

        .form-group
          = f.input :nav_location, collection: Page::NAV_LOCATIONS

        .form-group
          = f.submit "Update Page", class: 'btn btn-default'

app/views/admin/pages/index.html.haml
.row
  .col-xs-12.col-md-3
    = render 'side_nav'

  .col-xs-12.col-md-9
    #page-content
      %h1 Welcome to Creekstone Cookers Dashboard

:coffee
  $ ->
    $('.pages-sortable, .page-children').sortable({
      axis: 'y'
      handle: '.handle'
      update: ->
        pages = []
        $('.pages-sortable .page-title, .page-children .page-title').each ->
          pages.push($(this).data('page-id'))
        $.post($('.pages-sortable').data('update-url'),  { 'page[position]': pages } )
    });

app/views/admin/pages/new.html.haml
.row
  .col-xs-12.col-md-3
    = render 'side_nav'

  .col-xs-12.col-md-9
    #page-content
      %h2 Create A New Page

      = simple_form_for @page, :url => url_for(:action => 'create', :controller => 'pages'), html: { role: 'form' } do |f|
        .form-group
          = f.input :title, placeholder: 'Page Title', input_html: { style: 'width: 100%' }
        .form-group
          = f.input :content, :as => :ckeditor, input_html: { :ckeditor => {:toolbar => 'Full'} }

        .form-group
          = f.label :parent_id
          = f.collection_select :parent_id, Page.order(:title), :id, :title, include_blank: true
        .form-group
          = f.input :nav_location, collection: Page::NAV_LOCATIONS, include_blank: true
        .form-group
          = f.submit

app/views/contacts/new.html.haml
.col-md-4.col-md-offset-2
  = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
    .form-group
      = f.input :name, input_html: { class: 'form-control' }
    .form-group
      = f.input :email, input_html: { class: 'form-control' }
    .form-group
      = f.input :message, as: :text, input_html: { class: 'form-control' }
    .form-group
      = f.input :nickname, as: :hidden, :hint => 'Leave this field blank!'
    .form-group
      = f.button :submit, value: 'Submit', class: 'btn btn-default pull-right'

.col-md-4
  %h4 Thank you for visiting Creekstone Cookers.
  %p Please feel free to contact us with any questions or to just leave a comment. We look forward to hearing from you.
  %p
    = link_to 'laurie@creekstonecookers.com', 'mailto:laurie@creekstonecookers.com'
    %br
    = link_to '404.295.4453', 'tel:404.295.4453'

app/views/layouts/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58178071-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_footer.html.haml
.footer
  .container
    %hr

    / %ul.nav
    /   %li= link_to 'Home', root_url
    /   %li= link_to 'About Us', '#'
    /   %li= link_to 'Buying an AGA?', '#'
    /   %li= link_to 'View Models', '#'
    /   %li= link_to 'AGA Living', '#'
    /   %li= link_to 'Contact Us', '#'

    / %hr

    .copy.pull-left &copy; #{Time.now.year} Creekstone Cookers Inc.
    .pull-right
      = image_tag 'aga_logo.jpg', width: '60%'

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  .container
    %div.alert.fade.in{ "data-alert" => "alert", class: "#{twitterized_type(type)}", style: 'margin: 0 0 20px' }
      %button.close{ type: "button", "data-dismiss" => "alert", "aria-hidden" => "true"} &times;
      %p
        = message

app/views/layouts/_navigation.html.haml
.header
  .container
    = link_to root_url do
      = image_tag 'logo.png', class: 'logo', width: '180', height: '67'

    %ul.main-menu
      %li= link_to 'Home', root_url
      %li= link_to 'About Us', page_path('about-us')
      %li.topmenu
        = link_to 'Buying an AGA?', '#'
        .caret
        %ul.submenu
          %li= link_to 'AGA History', page_path('aga-history-timeline')
          %li= link_to 'AGA Cookers Explained', page_path('aga-cookers-explained')
          %li= link_to 'Reasons to Purchase an AGA', page_path('reasons-to-buy')
          %li= link_to '10 AGA Cooking Methods', page_path('10-aga-cooking-methods')
          %li= link_to 'Download a Brochure', '#'
          %li= link_to 'Current Promotions', '#'
      %li.topmenu
        = link_to 'View Models', '#'
        .caret
        %ul.submenu
          %li= link_to 'Dual Control', page_path('dual-control')
          %li= link_to 'Total Control', page_path('total-control')
          %li= link_to 'City24', page_path('city24')
          %li= link_to 'Companion', page_path('companion')
      %li.topmenu
        = link_to 'AGA Living', '#'
        .caret
        %ul.submenu
          %li= link_to 'Celebrity Owners', page_path('celebrity-aga-owners')
          %li= link_to 'Gallery', page_path('gallery')
          %li= link_to 'Testimonials', page_path('testimonials')
          %li= link_to 'Recipes', '#'

      %li= link_to 'Contact Us', contacts_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{style: "padding: 50px 0;"}

    .container
      = render 'layouts/messages'

      .row
        .col-xs-12.col-md-12
          = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    - if request.env['HTTP_HOST'] == 'www.creekstonecookers.com'
      = render 'layouts/analytics'

  %body

    = render 'layouts/navigation'
    = render 'layouts/messages'

    - unless params[:action] == "home"
      .container
        .row
          .col-md-12
            = yield
    - else
      = yield

    = render 'layouts/footer'

app/views/layouts/no_side_nav.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body

    = render 'layouts/navigation'
    = render 'layouts/messages'

    - unless params[:action] == "home"
      .container
        = yield
    - else
      = yield

    = render 'layouts/footer'

app/views/pages/_features.html.haml
%p Every AGA Cooker is made in exactly the same way it has always been: molten iron is poured into molds to create cast-iron. It's this iron that brings the AGA cooker's distinctive cooking performance and while most other cookers are spray painted in minutes, skilled AGA craftsman add multiple coats of vitreous enamel - a process that takes three days to complete.

%p Slow cooking is rooted into the AGA philosophy; it allows your food to gently cook without the risk of burning. So you can throw a dish together first thing in the morning, ignore it for hours on end and pull out a delicious meal by teatime. If you're in a rush, the high heat of the roasting oven is ideal for a pizza, or a grilled steak can be prepared using the boiling plate - even ready-meals can be cooked easily in an AGA Cooker.

%p
  %strong Roasting oven -
  roasts and grills beautifully and is big enough to fit a 13kg 28lb turkey. Radiant heat means food keeps its natural succulence and flavor.

%p
  %strong Baking oven -
  heated to an ideal moderate baking temperature - ideal for cakes, biscuits and bread.

%p
  %strong Slow Cook oven -
  Simmers perfectly by constantly maintaining the oven at just the right temperature for long, slow cooking. This develops flavours and will make even the toughest cut of meat melt-in-the-mouth tender.

%p
  %strong Warming oven -
  creates just the right temperature for safely warming plates and serving dishes and for keeping cooked food hot until ready to serve.

%p
  %strong What to expect
  %br
  From a toasted sandwich to a perfectly risen soufflé, an AGA Cooker excels at every style of cooking. AGA cakes are fluffier, stir-frys wonderfully fast, roasts more succulent and pizzas perfectly crisp. There's nothing an AGA oven cannot do - and everything it does, it does better.

%p
  %strong AGA ovens are easier to maintain
  %br
  Choose an AGA Cooker and you'll notice that the time you spend cleaning is greatly reduced. That's because the ovens and hotplates of an AGA Cooker are virtually self-cleaning. It's simply because they're always on - any spillages are carbonized, so all you have to do is give it the occasional brush out.

%p
  %strong No lingering food smells
  %br
  As you cook in your AGA ovens, food aromas are drawn away and extracted via the flue. This means if you're cooking something pungent like fish, the AGA Cooker will help keep smells to a minimum.

%p Depending on the model, different flue options are available - speak to your local AGA dealer for details.

%p For more details on how the AGA Cooker works, please watch our video:

.embed-responsive.embed-responsive-16by9
  %iframe.embed-responsive-item{src: '//www.youtube.com/embed/vmwiBYsd6Ys', allowfullscreen: '', style: 'max-width: 100%'}

app/views/pages/aga_companion.html.haml
%h2 AGA Companion
%h4 Classic AGA Cooker

%p Don't let this little range fool you. At 24" inches wide, it may be small in stature, but it's big on performance and style. This dual-fuel range features four versatile gas burners, one conventional oven with an integral broiler and one convection oven. And of course, it's made with that classic AGA design available in 11 delicious colors.

%p As a free-standing range it brings the versatility of dual-fuel cooking into any kitchen. Team a 2 Oven, 3 Oven or 4 Oven AGA with an AGA Companion and you have the ultimate versatility of cooking with radiant heat, a live gas flame and electric and all at once!

app/views/pages/city_sixty_contemporary.html.haml
.city_sixty_traditional.col-sm-12.col-md-6
  %h2 City60 AGA Cooker
  %h4 Cast-iron range cooker

  .image-container
    = image_tag 'city_sixty_traditional/city_trad_rose.jpg', class: 'img-responsive'
  .col-sm-12.clearfix
    %h4 Colors
    .color-chip.city60-rose.active{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Rose"}
    .color-chip.city60-lemon{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Lemon"}
    .color-chip.city60-black{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Black"}
    .color-chip.city60-cream{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Cream"}
    .color-chip.city60-pewter{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Pewter"}
    .color-chip.city60-darkblue{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Dark Blue"}
    .color-chip.city60-green{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "British Racing Green"}
    .color-chip.city60-pistachio{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Pistachio"}
    .color-chip.city60-aqua{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Aqua"}
    .color-chip.city60-heather{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Heather"}
    .color-chip.city60-aubergine{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Aubergine"}
    .color-chip.city60-pearl{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Pearl"}
    .color-chip.city60-white{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "White"}
    .color-chip.city60-duckegg{ 'data-toggle' => "tooltip", 'data-placement' => "top", title: "Duck Egg Blue"}

    %br
    %br

  .col-sm-12.clearfix
    %h4 Fuel Types
    %i.electric{style:'margin-left: 0'} Electric

    %br
    %br


  .col-sm-12.gallery.clearfix
    = link_to '/assets/60cm-roomset-1_866x428.jpg', 'data-imagelightbox' => "a", class: 'col-sm-3 thumbnail' do
      = image_tag '60cm-roomset-1_866x428.jpg'

    = link_to '/assets/60cm-roomset-2_866x428.jpg', 'data-imagelightbox' => "a", class: 'col-sm-3 thumbnail' do
      = image_tag '60cm-roomset-2_866x428.jpg'

.col-sm-12.col-md-6

  %p The AGA City60 couldn't be easier to use. With one control knob for the hotplates and another for the ovens, the cooker has been designed with simplicity in mind. The AGA City60's roasting/baking oven can be programmed and can have up to three events programmed per day*. They operate using a timer similar to that used for controlling a central heating programmer. This means the ovens can be timed to come on and ready to cook when you are.
  %small *Using the optional extra AGA City60 Programmer.

  %ul.nav.nav-tabs{role: "tablist"}
    %li.active
      %a{href: "#features", role: "tab", "data-toggle" => "tab"} Features
    %li
      %a{href: "#technical", role: "tab", "data-toggle" => "tab"} Specs
    %li
      %a{href: "#manuals", role: "tab", "data-toggle" => "tab"} Literature
    %li
      %a{href: "#accessories", role: "tab", "data-toggle" => "tab"} Accessories
    %li
      %a{href: "#contact", role: "tab", "data-toggle" => "tab"} Contact

  .tab-content
    .tab-pane.active#features
      %p The classic 4-oven AGA Cooker is the flagship of the AGA line. Based on a proven design of more than 80 years, the 4-oven AGA provides a truly unique and rewarding cooking experience. With 4 radiant-heat ovens, two hotplates and a warming plate this AGA has unmatched flexibility and cooking capabilities.

      = render 'features'

    .tab-pane#technical
      %h3 FOUR OVEN COOKER - GAS MODEL: SPECIFICATIONS
      .table-responsive
        %table.table
          %tr
            %td
              %strong DIMENSIONS
            %td 35"H × 24 1/2"D × 24"W
          %tr
            %td
              %strong NOTE
            %td Do not use the above specifications for kitchen design or installation. Please consult our design guide for detailed rough-in and specification information.
          %tr
            %td
              %strong MATERIALS
            %td Durable cast iron covered by three coats of vitreous enamel in one of 12 colors.
          %tr
            %td
              %strong MAINTENANCE
            %td An annnual and 10-year preventative maintainence are recommended.
          %tr
            %td
              %strong INSTALLATION
            %td Must be installed by a certified AGA fitter. Please note that using anyone other than a certified Aga fitter will void the product warranty.
          %tr
            %td
              %strong WEIGHT
            %td 492 lbs
          %tr
            %td
              %strong VENTING OPTIONS
            %td In room venting flue - electric
          %tr
            %td
              %strong FUEL OPTIONS
            %td Electric
          %tr
            %td
              %strong WARRANTY
            %td 5 years limited, parts and labour

    .tab-pane#manuals
      %p
        %a{href: "http://www.aga-ranges.com/media/185886/brochure_cooker_en.pdf", target: 'blank'} AGA Cooker Brochure
      %p
        %a{href: "http://www.aga-ranges.com/media/236667/misc_aga_total_control_how_aga_cooker_became_an_icon.pdf", target: 'blank'} How the AGA Cooker Became an Icon
      %p
        %a{href: "http://www.aga-ranges.com/media/236997/user_instructions_cooker_2_and_4_oven_gas.pdf", target: 'blank'} User and Care Guide
      %p
        %a{href: "http://www.aga-ranges.com/media/193152/installation_guide_cooker_2_and_4_oven_gas.pdf", target: 'blank'} Installation Instructions
      %p
        %a{href: "http://www.aga-ranges.com/media/237000/installation_guide_cooker_vent.pdf", target: 'blank'} Vent Installation Instructions
      %p
        %a{href: "http://www.aga-ranges.com/media/237039/misc_aga_design_guide.pdf", target: 'blank'} Design Guide

    .tab-pane#accessories
    .tab-pane#contact

app/views/pages/edit.html.haml
%h2 Edit Page

%h5= link_to 'View Page', page_path(@page)

= simple_form_for @page, html: { role: 'form' } do |f|
  .form-group
    = f.input :title, placeholder: 'Page Title', input_html: { style: 'width: 100%' }
    = f.input :content, :as => :ckeditor, input_html: { :ckeditor => {:toolbar => 'Full'} }

    = f.submit

app/views/pages/new.html.haml
%h2 Create A New Page

= simple_form_for @page, html: { role: 'form' } do |f|
  .form-group
    = f.input :title, placeholder: 'Page Title', input_html: { style: 'width: 100%' }
    = f.input :content, :as => :ckeditor, input_html: { :ckeditor => {:toolbar => 'Full'} }

    = f.submit

app/views/pages/show.html.haml
- provide :title, @page.title

= @page.content.html_safe

app/views/pages/update_image.js.haml
$('.image-container img').attr('src', "#{j(image_path(@image))}")